default_agent: multi_agent_app
agents:
  multi_agent_app:
    name: multi_agent_app
    entrypoint: multi_agent_app.py
    platform: linux/arm64
    container_runtime: none
    aws:
      execution_role: arn:aws:iam::047786098634:role/municipal-policy-ai-agentcore-role
      execution_role_auto_create: true
      account: 047786098634
      region: us-west-2
      ecr_repository: 047786098634.dkr.ecr.us-west-2.amazonaws.com/bedrock-agentcore-multi_agent_app
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: multi_agent_app-grDIat649D
      agent_arn: arn:aws:bedrock-agentcore:us-west-2:047786098634:runtime/multi_agent_app-grDIat649D
      agent_session_id: 258359fd-cfc4-4a9a-abe1-e8c88597a8ff
    codebuild:
      project_name: bedrock-agentcore-multi_agent_app-builder
      execution_role: arn:aws:iam::047786098634:role/AmazonBedrockAgentCoreSDKCodeBuild-us-west-2-8e6aba1f5a
      source_bucket: bedrock-agentcore-codebuild-sources-047786098634-us-west-2
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
