default_agent: app
agents:
  app:
    name: app
    entrypoint: app.py
    platform: linux/arm64
    container_runtime: none
    aws:
      execution_role: arn:aws:iam::047786098634:role/AmazonBedrockAgentCoreSDKRuntime-us-west-2-a172cedcae
      execution_role_auto_create: false
      account: 047786098634
      region: us-west-2
      ecr_repository: 047786098634.dkr.ecr.us-west-2.amazonaws.com/bedrock-agentcore-app
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: app-3oJHjL6TFx
      agent_arn: arn:aws:bedrock-agentcore:us-west-2:047786098634:runtime/app-3oJHjL6TFx
      agent_session_id: fe9623fa-77f0-4d82-a606-24dbe64b2e92
    codebuild:
      project_name: bedrock-agentcore-app-builder
      execution_role: arn:aws:iam::047786098634:role/AmazonBedrockAgentCoreSDKCodeBuild-us-west-2-a172cedcae
      source_bucket: bedrock-agentcore-codebuild-sources-047786098634-us-west-2
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
